from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any, Dict, Protocol
from LabviewToPython.core.events.eventbus import IEventBus


class ICameraService(ABC):
    """High-level camera service (wraps a device driver, handles acquisition threading)."""
    def __init__(self, bus: IEventBus) -> None: ...
    @abstractmethod
    def open(self) -> None: ...
    @abstractmethod
    def start(self) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...
    @abstractmethod
    def close(self) -> None: ...
    @abstractmethod
    def set_params(self, **params: Any) -> None: ...


class IPressureService(ABC):
    def __init__(self, bus: IEventBus) -> None: ...
    @abstractmethod
    def start_polling(self, interval_ms: int = 500) -> None: ...
    @abstractmethod
    def stop_polling(self) -> None: ...


class IMotionService(ABC):
    def __init__(self, bus: IEventBus) -> None: ...
    @abstractmethod
    def home(self) -> None: ...
    @abstractmethod
    def move_to(self, position: float) -> None: ...
    @abstractmethod
    def read_position(self) -> float: ...


class IPumpService(ABC):
    def __init__(self, bus: IEventBus) -> None: ...
    @abstractmethod
    def start(self) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...
    @abstractmethod
    def read_status(self) -> Dict[str, Any]: ...


class IAnalysisService(ABC):
    def __init__(self, bus: IEventBus) -> None: ...
    @abstractmethod
    def submit_frame(self, frame: "object") -> None: ...


class IDataStore(ABC):
    def __init__(self, bus: IEventBus) -> None: ...
    @abstractmethod
    def write_meta(self, record: Dict[str, Any]) -> None: ...
    @abstractmethod
    def write_result(self, record: Dict[str, Any]) -> None: ...


class IScanScheduler(ABC):
    def __init__(self, bus: IEventBus) -> None: ...
    @abstractmethod
    def schedule(self, plan: Dict[str, Any]) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...


# Optional: a tiny protocol that views use to talk to VMs (keeps views independent in tests)
class HasTitle(Protocol):
    @property
    def title(self) -> str: ...
