from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any, Dict


class Camera(ABC):
    @abstractmethod
    def open(self) -> None: ...
    @abstractmethod
    def start(self) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...
    @abstractmethod
    def close(self) -> None: ...
    @abstractmethod
    def set_params(self, **params: Any) -> None: ...


class PressureSensor(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def read(self) -> float: ...
    @abstractmethod
    def info(self) -> Dict[str, Any]: ...


class Pump(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def start(self) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...
    @abstractmethod
    def status(self) -> Dict[str, Any]: ...


class StepperMotor(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def home(self) -> None: ...
    @abstractmethod
    def move_to(self, position: float) -> None: ...
    @abstractmethod
    def position(self) -> float: ...
